version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    
    ports:
      - '80:80'
    restart: always
    depends_on:
      - front
  back:
    build:
        dockerfile: ./back/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5433; do sleep 1; done; cd back && python ./api.py'
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://test:test@db:5433/test
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5433
    expose:
      - 5433
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    command: -p 5433
volumes:
  postgres_data: